// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
/// A struct that holds a challenge string and its expiration time.
pub struct ChallengeString {
    /// The challenge, as generated by the polyproto home server.
    pub challenge: String,
    /// An expiry date in seconds since the Unix epoch, after which the challenge cannot be completed
    /// any longer.
    pub expires: u64,
}
