name: Build and Test (nextest)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          prefix-key: "linux"
      - uses: taiki-e/install-action@nextest
      - name: nextest run
        run: |
          cargo nextest run --all-features --failure-output final --no-fail-fast

  # wasm:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: Swatinem/rust-cache@v2
  #       with:
  #         cache-all-crates: "true"
  #         prefix-key: "macos"
  #     - name: Run WASM tests with Safari, Firefox, Chrome
  #       run: |
  #         rustup target add wasm32-unknown-unknown
  #         curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
  #         cargo binstall --no-confirm wasm-bindgen-cli --version "0.2.88" --force
  #         cargo binstall --no-confirm wasm-pack --force
  #         wasm-pack test --node -- --features wasm --examples
  #         wasm-pack test --firefox -- --features wasm --examples
  #         wasm-pack test --chrome -- --features wasm --examples
  #         wasm-pack test --node -- --features wasm
  #         wasm-pack test --firefox -- --features wasm
  #         wasm-pack test --chrome -- --features wasm
